//! K11 DMA domains and bounded mappings.
use crate::{device::DeviceId,memory::FrameAllocator};
pub const MAX_DMA_DOMAINS:usize=128;pub const MAX_DMA_MAPPINGS:usize=64;
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum DmaDirection{ToDevice,FromDevice,Bidirectional}
#[derive(Clone,Copy,Debug)]pub struct DmaMapping{pub physical:u64,pub bytes:u64,pub direction:DmaDirection,pub active:bool}impl DmaMapping{pub const EMPTY:Self=Self{physical:0,bytes:0,direction:DmaDirection::Bidirectional,active:false};}
#[derive(Clone,Copy)]pub struct DmaDomain{pub device:DeviceId,pub address_bits:u8,pub coherent:bool,pub enabled:bool,mappings:[DmaMapping;MAX_DMA_MAPPINGS]}impl DmaDomain{pub const EMPTY:Self=Self{device:DeviceId(0),address_bits:0,coherent:false,enabled:false,mappings:[DmaMapping::EMPTY;MAX_DMA_MAPPINGS]};pub fn map_contiguous(&mut self,allocator:&mut FrameAllocator,bytes:u64,direction:DmaDirection)->Result<DmaMapping,&'static str>{if !self.enabled||bytes==0{return Err("DMA domain unavailable")}let pages=bytes.checked_add(4095).ok_or("DMA size overflow")?/4096;let physical=allocator.allocate_contiguous(pages).ok_or("DMA allocation failed")?;let end=physical.checked_add(pages*4096-1).ok_or("DMA address overflow")?;if self.address_bits<64&&end>=(1u64<<self.address_bits){allocator.deallocate_contiguous(physical,pages)?;return Err("DMA mask exceeded")}let m=DmaMapping{physical,bytes:pages*4096,direction,active:true};let slot=self.mappings.iter_mut().find(|x|!x.active).ok_or("DMA mapping table full")?;*slot=m;Ok(m)}pub fn unmap(&mut self,allocator:&mut FrameAllocator,physical:u64)->Result<(),&'static str>{let m=self.mappings.iter_mut().find(|x|x.active&&x.physical==physical).ok_or("DMA mapping not found")?;allocator.deallocate_contiguous(m.physical,m.bytes/4096)?;m.active=false;Ok(())}}
pub struct DmaManager{domains:[DmaDomain;MAX_DMA_DOMAINS]}impl DmaManager{pub const fn new()->Self{Self{domains:[DmaDomain::EMPTY;MAX_DMA_DOMAINS]}}pub fn create_domain(&mut self,device:DeviceId,address_bits:u8,coherent:bool)->Result<&mut DmaDomain,&'static str>{if !(32..=64).contains(&address_bits){return Err("invalid DMA mask")}let d=self.domains.iter_mut().find(|d|!d.enabled).ok_or("DMA domain table full")?;*d=DmaDomain{device,address_bits,coherent,enabled:true,mappings:[DmaMapping::EMPTY;MAX_DMA_MAPPINGS]};Ok(d)}pub fn revoke(&mut self,device:DeviceId)->Result<(),&'static str>{let d=self.domains.iter_mut().find(|d|d.enabled&&d.device==device).ok_or("DMA domain not found")?;if d.mappings.iter().any(|m|m.active){return Err("DMA mappings still active")}d.enabled=false;Ok(())}}
impl DmaManager {
 pub fn domain_for(&mut self,device:DeviceId)->Option<&mut DmaDomain>{self.domains.iter_mut().find(|d|d.enabled&&d.device==device)}
 /// Emergency teardown after bus mastering is disabled or IOMMU translation
 /// has been revoked. Returns all kernel-owned bounce pages.
 pub fn force_revoke(&mut self,allocator:&mut FrameAllocator,device:DeviceId)->Result<usize,&'static str>{let d=self.domain_for(device).ok_or("DMA domain not found")?;let mut n=0;for m in &mut d.mappings{if m.active{allocator.deallocate_contiguous(m.physical,m.bytes/4096)?;m.active=false;n+=1}}d.enabled=false;Ok(n)}
}
