//! K14.C31 graphics + compute execution qualification.
//!
//! C31 makes command encoding, separate compute/graphics queues, owned shader
//! upload, pipeline state, compute dispatch, graphics draw, display sync and the
//! shader cache/precache path executable in QEMU. The executor is explicitly the
//! Titanweave reference backend over real C28 GTT/C30 scanout memory. Physical
//! Radeon CP/GFX/MEC queue programming and native AMD ISA execution remain false
//! until their exact firmware/page-table/privileged-register prerequisites are
//! live; C31 never re-labels reference execution as silicon execution.

use titanweave_boot_protocol::BootInfo;
use crate::{memory::FrameAllocator,native_gpu_c30,radeon_command,radeon_compute,radeon_compute_caps,radeon_graphics,radeon_shader_cache,serial,sync::SpinLock};
pub const K14C31_ABI_VERSION:u32=1;
pub const RADEON_C31_REFERENCE_EXECUTION:bool=true;
pub const RADEON_C31_NATIVE_AMD_ISA:bool=false;
pub const RADEON_C31_PHYSICAL_CP_QUEUES:bool=false;
pub const RADEON_C31_PRIVILEGED_GFX_MMIO:bool=false;
pub const RADEON_C31_GPU_PAGE_TABLE_PROGRAMMING:bool=false;
pub const RADEON_C31_SHADER_PRECACHE:bool=true;
pub const RADEON_C31_HIP_STYLE_CAPABILITY_MODEL:bool=true;
pub const RADEON_C31_PLACEHOLDER_SUBSYSTEMS:u8=0;
#[derive(Clone,Copy,Debug)]pub struct C31State{pub c30_verified:bool,pub amd_present:bool,pub shader_upload_verified:bool,pub shader_cache_verified:bool,pub precache_entries:u64,pub command_encoding_verified:bool,pub compute_queue_verified:bool,pub compute_dispatch_verified:bool,pub compute_elements:u32,pub compute_hash:u64,pub graphics_queue_verified:bool,pub graphics_draw_verified:bool,pub triangle_pixels:u64,pub framebuffer_verified:bool,pub framebuffer_hash:u64,pub timeline_fences_verified:bool,pub display_sync_verified:bool,pub capability_model_ready:bool,pub reference_execution:bool,pub physical_gpu_execution:bool,pub hardware_deferred:bool,pub qualified:bool,pub fingerprint:u64}
impl C31State{pub const EMPTY:Self=Self{c30_verified:false,amd_present:false,shader_upload_verified:false,shader_cache_verified:false,precache_entries:0,command_encoding_verified:false,compute_queue_verified:false,compute_dispatch_verified:false,compute_elements:0,compute_hash:0,graphics_queue_verified:false,graphics_draw_verified:false,triangle_pixels:0,framebuffer_verified:false,framebuffer_hash:0,timeline_fences_verified:false,display_sync_verified:false,capability_model_ready:false,reference_execution:false,physical_gpu_execution:false,hardware_deferred:true,qualified:false,fingerprint:0};}
static STATE:SpinLock<C31State>=SpinLock::new(C31State::EMPTY);fn mix(mut h:u64,v:u64)->u64{h^=v;h=h.wrapping_mul(0x100000001b3);h}
fn policy()->Result<(),&'static str>{if K14C31_ABI_VERSION!=1||!RADEON_C31_REFERENCE_EXECUTION||RADEON_C31_NATIVE_AMD_ISA||RADEON_C31_PHYSICAL_CP_QUEUES||RADEON_C31_PRIVILEGED_GFX_MMIO||RADEON_C31_GPU_PAGE_TABLE_PROGRAMMING||!RADEON_C31_SHADER_PRECACHE||!RADEON_C31_HIP_STYLE_CAPABILITY_MODEL||RADEON_C31_PLACEHOLDER_SUBSYSTEMS!=0{return Err("K14.C31 authority/no-stub policy invalid")}Ok(())}
pub fn initialize(allocator:&mut FrameAllocator<'_>,boot_info:&BootInfo)->Result<C31State,&'static str>{
 policy()?;let c30=native_gpu_c30::state();if !c30.qualified{return Err("K14.C31 requires frozen qualified C30")};let owner=if crate::native_gpu_c27::state().forge_device!=0{crate::native_gpu_c27::state().forge_device}else{0xc030};let caps=radeon_compute_caps::current()?;let qfp=radeon_command::queue_self_test()?;let scfp=radeon_shader_cache::self_test()?;let compute=radeon_compute::qualify(allocator,owner)?;let graphics=radeon_graphics::qualify(allocator,boot_info,owner,c30)?;let(ins,hits,miss,precache)=radeon_shader_cache::counters();if ins<3||hits<1||precache<3{return Err("C31 live shader cache/precache counters invalid")};
 let mut s=C31State{c30_verified:true,amd_present:c30.amd_present,shader_upload_verified:compute.shader_object!=0&&graphics.vertex_shader!=0&&graphics.pixel_shader!=0,shader_cache_verified:scfp!=0&&hits>=1,precache_entries:precache,command_encoding_verified:compute.command_object!=0&&graphics.command_object!=0&&qfp!=0,compute_queue_verified:compute.queue_submitted==1&&compute.queue_retired==1,compute_dispatch_verified:compute.verified,compute_elements:compute.elements,compute_hash:compute.result_hash,graphics_queue_verified:graphics.queue_submitted==1&&graphics.queue_retired==1,graphics_draw_verified:graphics.verified,triangle_pixels:graphics.triangle_pixels,framebuffer_verified:graphics.live_hash!=0,framebuffer_hash:graphics.live_hash,timeline_fences_verified:compute.fence>0&&graphics.fence>0,display_sync_verified:c30.scanout_verified&&graphics.render_target==c30.back_object,capability_model_ready:caps.source_stable&&caps.separate_compute_queue&&caps.separate_graphics_queue&&caps.timeline_fence&&caps.shader_precache&&!caps.native_amd_isa&&!caps.physical_dispatch,reference_execution:true,physical_gpu_execution:false,hardware_deferred:c30.amd_present,..C31State::EMPTY};
 serial::println(format_args!("[C31SH] shader/resource model: upload={} cache={} precache_entries={} native_AMD_ISA=false objects={}/{}/{}",s.shader_upload_verified,s.shader_cache_verified,s.precache_entries,compute.shader_object,graphics.vertex_shader,graphics.pixel_shader));
 serial::println(format_args!("[C31CQ] compute queue: verified={} submitted={} retired={} fence={} command_object={}",s.compute_queue_verified,compute.queue_submitted,compute.queue_retired,compute.fence,compute.command_object));
 serial::println(format_args!("[C31CP] compute execution: verified={} elements={} groups={} result_hash={:#018x} backend=reference-GTT",s.compute_dispatch_verified,s.compute_elements,compute.groups,s.compute_hash));
 serial::println(format_args!("[C31GQ] graphics queue: verified={} submitted={} retired={} fence={} command_object={}",s.graphics_queue_verified,graphics.queue_submitted,graphics.queue_retired,graphics.fence,graphics.command_object));
 serial::println(format_args!("[C31GX] graphics execution: verified={} triangle_pixels={} render_target={} live_framebuffer={} framebuffer_hash={:#018x}",s.graphics_draw_verified,s.triangle_pixels,graphics.render_target,s.framebuffer_verified,s.framebuffer_hash));
 serial::println(format_args!("[C31HC] compute capability model: address_bits={} dimensions={} max_workgroup={} separate_compute={} separate_graphics={} timeline_fence={} host_visible_GTT={} native_AMD_ISA={} physical_dispatch={}",caps.address_bits,caps.dispatch_dimensions,caps.max_workgroup_x,caps.separate_compute_queue,caps.separate_graphics_queue,caps.timeline_fence,caps.host_visible_gtt,caps.native_amd_isa,caps.physical_dispatch));
 serial::println(format_args!("[C31SC] shader cache/precache: insertions={} hits={} misses={} precache={} future_HIP_style_caps={}",ins,hits,miss,precache,s.capability_model_ready));
 serial::println(format_args!("[C31PG] execution authority: reference_backend=true physical_CP=false native_AMD_ISA=false privileged_GFX_MMIO=false GPU_page_table_programming=false physical_GPU_execution=false placeholders=0"));
 let common=s.c30_verified&&s.shader_upload_verified&&s.shader_cache_verified&&s.precache_entries>=3&&s.command_encoding_verified&&s.compute_queue_verified&&s.compute_dispatch_verified&&s.compute_elements==radeon_compute::C31_COMPUTE_ELEMENTS&&s.compute_hash!=0&&s.graphics_queue_verified&&s.graphics_draw_verified&&s.triangle_pixels>=512&&s.framebuffer_verified&&s.framebuffer_hash!=0&&s.timeline_fences_verified&&s.display_sync_verified&&s.capability_model_ready&&s.reference_execution&&!s.physical_gpu_execution;
 if !common{return Err("K14.C31 graphics+compute execution gates did not close")};let mut fp=0xc031_4750_5545_0001u64;for v in [caps.fingerprint,qfp,scfp,s.compute_hash,s.framebuffer_hash,s.triangle_pixels,s.precache_entries,u64::from(s.compute_elements)]{fp=mix(fp,v)}s.fingerprint=fp;s.qualified=fp!=0;serial::println(format_args!("[C31RD] K14.C31 graphics+compute execution ready: compute={} graphics={} framebuffer={} shader_cache={} reference={} physical_GPU={} qualified={} fingerprint={:#018x}",s.compute_dispatch_verified,s.graphics_draw_verified,s.framebuffer_verified,s.shader_cache_verified,s.reference_execution,s.physical_gpu_execution,s.qualified,s.fingerprint));*STATE.lock()=s;Ok(s)
}
pub fn state()->C31State{*STATE.lock()}pub fn packed_status()->u64{let s=state();let mut v=0u64;if s.amd_present{v|=1}if s.shader_upload_verified{v|=1<<1}if s.compute_dispatch_verified{v|=1<<2}if s.graphics_draw_verified{v|=1<<3}if s.framebuffer_verified{v|=1<<4}if s.shader_cache_verified{v|=1<<5}if s.reference_execution{v|=1<<6}if s.physical_gpu_execution{v|=1<<7}if s.hardware_deferred{v|=1<<8}if s.qualified{v|=1<<13}v|(s.precache_entries<<16)|(u64::from(s.compute_elements)<<32)}
