//! K14.C32 production/stability + final K14 Radeon qualification.
//!
//! C32 freezes the userspace status/capability ABI and executes bounded stress
//! across queues, GTT/VRAM allocation, software IRQ accounting, recovery state,
//! graphics/compute coexistence and display presentation.  QEMU qualifies the
//! complete Titanweave reference/control-plane foundation. Physical Radeon
//! silicon stress remains an explicit status bit and separate bare-metal proof;
//! it is never inferred from QEMU.

use titanweave_boot_protocol::BootInfo;
use crate::{memory::FrameAllocator,native_gpu_c31,radeon_gpu_abi,radeon_multigpu,radeon_power,radeon_shader_cache,radeon_stability,radeon_telemetry,serial,sync::SpinLock};

pub const K14C32_ABI_VERSION:u32=1;
pub const RADEON_C32_PRODUCTION_STABILITY:bool=true;
pub const RADEON_C32_USER_ABI_FROZEN:bool=true;
pub const RADEON_C32_CAPABILITY_MODEL_FROZEN:bool=true;
pub const RADEON_C32_MULTI_GPU_GROUNDWORK:bool=true;
pub const RADEON_C32_BARE_METAL_SUITE_READY:bool=true;
pub const RADEON_C32_PHYSICAL_STRESS_QUALIFIED_BY_QEMU:bool=false;
pub const RADEON_C32_PLACEHOLDER_SUBSYSTEMS:u8=0;

#[derive(Clone,Copy,Debug)]pub struct C32State{
 pub c31_verified:bool,pub amd_present:bool,pub queue_stress_verified:bool,pub queue_submissions:u64,pub queue_retires:u64,
 pub memory_pressure_verified:bool,pub gtt_pressure_bytes:u64,pub vram_pressure_verified:bool,pub vram_pressure_deferred:bool,
 pub hang_recovery_verified:bool,pub recovery_cycles:u32,pub interrupt_stress_verified:bool,pub interrupt_events:u64,
 pub display_compute_concurrency:bool,pub graphics_compute_concurrency:bool,pub concurrency_rounds:u32,pub display_stress_verified:bool,pub display_presents:u32,
 pub multi_display_verified:bool,pub multi_display_connectors:u8,pub multi_gpu_enumeration_verified:bool,pub display_adapters:u8,pub amd_adapters:u8,
 pub power_policy_verified:bool,pub telemetry_verified:bool,pub telemetry_events:u64,pub telemetry_errors:u64,pub shader_precache_frozen:bool,pub precache_entries:u64,
 pub userspace_abi_frozen:bool,pub capability_model_frozen:bool,pub bare_metal_suite_ready:bool,pub physical_stress_qualified:bool,pub hardware_deferred:bool,
 pub qualified:bool,pub fingerprint:u64,
}
impl C32State{pub const EMPTY:Self=Self{c31_verified:false,amd_present:false,queue_stress_verified:false,queue_submissions:0,queue_retires:0,memory_pressure_verified:false,gtt_pressure_bytes:0,vram_pressure_verified:false,vram_pressure_deferred:true,hang_recovery_verified:false,recovery_cycles:0,interrupt_stress_verified:false,interrupt_events:0,display_compute_concurrency:false,graphics_compute_concurrency:false,concurrency_rounds:0,display_stress_verified:false,display_presents:0,multi_display_verified:false,multi_display_connectors:0,multi_gpu_enumeration_verified:false,display_adapters:0,amd_adapters:0,power_policy_verified:false,telemetry_verified:false,telemetry_events:0,telemetry_errors:0,shader_precache_frozen:false,precache_entries:0,userspace_abi_frozen:false,capability_model_frozen:false,bare_metal_suite_ready:false,physical_stress_qualified:false,hardware_deferred:true,qualified:false,fingerprint:0};}
static STATE:SpinLock<C32State>=SpinLock::new(C32State::EMPTY);
fn mix(mut h:u64,v:u64)->u64{h^=v;h=h.wrapping_mul(0x100000001b3);h}
fn policy()->Result<(),&'static str>{if K14C32_ABI_VERSION!=1||!RADEON_C32_PRODUCTION_STABILITY||!RADEON_C32_USER_ABI_FROZEN||!RADEON_C32_CAPABILITY_MODEL_FROZEN||!RADEON_C32_MULTI_GPU_GROUNDWORK||!RADEON_C32_BARE_METAL_SUITE_READY||RADEON_C32_PHYSICAL_STRESS_QUALIFIED_BY_QEMU||RADEON_C32_PLACEHOLDER_SUBSYSTEMS!=0{return Err("K14.C32 production/final policy invalid")}Ok(())}

pub fn initialize(allocator:&mut FrameAllocator<'_>,boot_info:&BootInfo)->Result<C32State,&'static str>{
 policy()?;let c31=native_gpu_c31::state();if !c31.qualified{return Err("K14.C32 requires frozen qualified C31")};let owner={let d=crate::native_gpu_c27::state();if d.forge_device!=0{d.forge_device}else{0xc030}};
 let tele_self=radeon_telemetry::self_test()?;let power_self=radeon_power::self_test()?;let mg_self=radeon_multigpu::self_test()?;let abi=radeon_gpu_abi::frozen()?;let stability=radeon_stability::qualify(allocator,boot_info,owner,crate::native_gpu_c30::state())?;let power=radeon_power::initialize_runtime()?;let inventory=radeon_multigpu::enumerate()?;let(_,_,_,precache)=radeon_shader_cache::counters();let telemetry=radeon_telemetry::snapshot();
 let physical_stress=c31.amd_present&&c31.physical_gpu_execution&&stability.vram_pressure_verified&&!stability.vram_pressure_deferred;let hardware_deferred=!physical_stress;
 let mut s=C32State{c31_verified:true,amd_present:c31.amd_present,queue_stress_verified:stability.queue_stress_verified,queue_submissions:stability.queue_submissions,queue_retires:stability.queue_retires,memory_pressure_verified:stability.gtt_pressure_verified&&(stability.vram_pressure_verified||stability.vram_pressure_deferred),gtt_pressure_bytes:stability.gtt_pressure_bytes,vram_pressure_verified:stability.vram_pressure_verified,vram_pressure_deferred:stability.vram_pressure_deferred,hang_recovery_verified:stability.hang_detected&&stability.hang_recovered,recovery_cycles:stability.recovery_cycles,interrupt_stress_verified:stability.interrupt_stress_verified,interrupt_events:stability.interrupt_events,display_compute_concurrency:stability.display_compute_concurrency,graphics_compute_concurrency:stability.graphics_compute_concurrency,concurrency_rounds:stability.concurrency_rounds,display_stress_verified:stability.display_stress_verified,display_presents:stability.display_presents,multi_display_verified:stability.multi_display_framework_verified,multi_display_connectors:stability.multi_display_connectors,multi_gpu_enumeration_verified:inventory.fingerprint!=0,display_adapters:inventory.display_adapters,amd_adapters:inventory.amd_adapters,power_policy_verified:power.state==radeon_power::PowerState::Active&&!power.physical_smu_programmed,telemetry_verified:telemetry.fingerprint!=0&&telemetry.errors==0,telemetry_events:telemetry.events_recorded,telemetry_errors:telemetry.errors,shader_precache_frozen:c31.shader_cache_verified&&precache>=3,precache_entries:precache,userspace_abi_frozen:abi.version==1&&abi.syscall==43,capability_model_frozen:c31.capability_model_ready&&abi.capability_mask==abi.stable_mask,bare_metal_suite_ready:true,physical_stress_qualified:physical_stress,hardware_deferred,qualified:false,fingerprint:0};
 serial::println(format_args!("[C32QS] queue stability: verified={} submitted={} retired={} wraps={} hang_detected={} hang_recovered={} abandoned={}",s.queue_stress_verified,s.queue_submissions,s.queue_retires,stability.queue_wraps,stability.hang_detected,stability.hang_recovered,stability.abandoned_on_reset));
 serial::println(format_args!("[C32MP] memory pressure: verified={} GTT_bytes={} VRAM_verified={} VRAM_deferred={} VRAM_bytes={}",s.memory_pressure_verified,s.gtt_pressure_bytes,s.vram_pressure_verified,s.vram_pressure_deferred,stability.vram_pressure_bytes));
 serial::println(format_args!("[C32RC] recovery+interrupt stress: hang_recovery={} recovery_cycles={} IRQ_verified={} IRQ_events={} physical_ASIC_reset=false physical_IH=false",s.hang_recovery_verified,s.recovery_cycles,s.interrupt_stress_verified,s.interrupt_events));
 serial::println(format_args!("[C32CX] concurrency: display_compute={} graphics_compute={} rounds={} compute_ops={} graphics_pixels={} display_presents={}",s.display_compute_concurrency,s.graphics_compute_concurrency,s.concurrency_rounds,stability.compute_ops,stability.graphics_pixels,s.display_presents));
 serial::println(format_args!("[C32MD] display stability: verified={} framework_connectors={} PCI_display_adapters={} AMD_adapters={} peer_DMA={} cross_GPU_execution={}",s.multi_display_verified,s.multi_display_connectors,s.display_adapters,s.amd_adapters,inventory.peer_dma_enabled,inventory.cross_gpu_execution_enabled));
 serial::println(format_args!("[C32PM] power policy: verified={} state={:?} transitions={} physical_SMU_programming={}",s.power_policy_verified,power.state,power.transitions,power.physical_smu_programmed));
 serial::println(format_args!("[C32TL] telemetry/diagnostics: verified={} events={} errors={} queue_submits={} queue_retires={} hangs={}/{} compute_ops={} graphics_pixels={} bytes_touched={}",s.telemetry_verified,s.telemetry_events,s.telemetry_errors,telemetry.queue_submits,telemetry.queue_retires,telemetry.hangs_detected,telemetry.hangs_recovered,telemetry.compute_operations,telemetry.graphics_pixels,telemetry.bytes_touched));
 serial::println(format_args!("[C32AB] frozen GPU ABI/capabilities: ABI_version={} syscall={} userspace_frozen={} capability_frozen={} shader_precache={} precache_entries={} bare_metal_suite_ready={}",abi.version,abi.syscall,s.userspace_abi_frozen,s.capability_model_frozen,s.shader_precache_frozen,s.precache_entries,s.bare_metal_suite_ready));
 serial::println(format_args!("[C32PG] final authority: reference_production_stability=true physical_stress_qualified={} hardware_deferred={} physical_ASIC_reset=false physical_IH=false physical_SMU=false peer_DMA=false cross_GPU_execution=false placeholders=0",s.physical_stress_qualified,s.hardware_deferred));
 let common=s.c31_verified&&s.queue_stress_verified&&s.queue_submissions==s.queue_retires&&s.memory_pressure_verified&&s.hang_recovery_verified&&s.recovery_cycles>=32&&s.interrupt_stress_verified&&s.interrupt_events>=1024&&s.display_compute_concurrency&&s.graphics_compute_concurrency&&s.concurrency_rounds>=64&&s.display_stress_verified&&s.display_presents>=16&&s.multi_display_verified&&s.multi_display_connectors==4&&s.multi_gpu_enumeration_verified&&s.power_policy_verified&&s.telemetry_verified&&s.telemetry_errors==0&&s.shader_precache_frozen&&s.precache_entries>=3&&s.userspace_abi_frozen&&s.capability_model_frozen&&s.bare_metal_suite_ready;
 if !common{return Err("K14.C32 production/stability gates did not close")}
 let mut fp=0xc032_4649_4e41_0001u64;for v in [c31.fingerprint,stability.fingerprint,inventory.fingerprint,power.fingerprint,telemetry.fingerprint,abi.fingerprint,tele_self,power_self,mg_self,s.queue_submissions,s.gtt_pressure_bytes,s.interrupt_events,u64::from(s.recovery_cycles),u64::from(s.display_presents),s.precache_entries]{fp=mix(fp,v)}s.fingerprint=fp;s.qualified=fp!=0;
 serial::println(format_args!("[C32RD] K14.C32 production/stability final ready: C31={} queue={} pressure={} recovery={} concurrency={} display={} telemetry={} ABI={} multiGPU={} physical_stress={} qualified={} fingerprint={:#018x}",s.c31_verified,s.queue_stress_verified,s.memory_pressure_verified,s.hang_recovery_verified,s.display_compute_concurrency&&s.graphics_compute_concurrency,s.display_stress_verified,s.telemetry_verified,s.userspace_abi_frozen,s.multi_gpu_enumeration_verified,s.physical_stress_qualified,s.qualified,s.fingerprint));
 *STATE.lock()=s;Ok(s)
}
pub fn state()->C32State{*STATE.lock()}
pub fn packed_status()->u64{let s=state();let mut v=0u64;if s.amd_present{v|=1}if s.queue_stress_verified{v|=radeon_gpu_abi::CAP_QUEUE_STRESS}if s.memory_pressure_verified{v|=radeon_gpu_abi::CAP_MEMORY_PRESSURE}if s.hang_recovery_verified{v|=radeon_gpu_abi::CAP_RECOVERY}if s.display_compute_concurrency&&s.graphics_compute_concurrency{v|=radeon_gpu_abi::CAP_CONCURRENCY}if s.multi_display_verified{v|=radeon_gpu_abi::CAP_MULTI_DISPLAY}if s.telemetry_verified{v|=radeon_gpu_abi::CAP_TELEMETRY}if s.power_policy_verified{v|=radeon_gpu_abi::CAP_POWER_POLICY}if s.multi_gpu_enumeration_verified{v|=radeon_gpu_abi::CAP_MULTI_GPU_ENUM}if s.shader_precache_frozen{v|=radeon_gpu_abi::CAP_SHADER_PRECACHE}if s.hardware_deferred{v|=radeon_gpu_abi::CAP_HARDWARE_DEFERRED}if s.physical_stress_qualified{v|=radeon_gpu_abi::CAP_PHYSICAL_STRESS_QUALIFIED}if s.bare_metal_suite_ready{v|=radeon_gpu_abi::CAP_BARE_METAL_SUITE_READY}if s.qualified{v|=radeon_gpu_abi::CAP_QUALIFIED}v|(u64::from(s.display_adapters)<<16)|(u64::from(s.amd_adapters)<<24)|(u64::from(s.display_presents)<<32)}
