//! K14.C31 executable graphics path over C30's real GTT scanout.
use core::ptr;
use titanweave_boot_protocol::BootInfo;
use crate::{framebuffer::Framebuffer,memory::FrameAllocator,native_gpu_c30::C30State,radeon_command::{CommandBuffer,CommandOpcode,ExecutionQueue,QueueClass},radeon_fence::RadeonFenceTimeline,radeon_memory,radeon_pipeline,radeon_shader::{self,ReferenceShaderKind,ShaderStage},radeon_shader_cache};
pub const RADEON_GRAPHICS_ABI_VERSION:u32=1;
#[derive(Clone,Copy,Debug)]pub struct GraphicsQualification{pub vertex_shader:u64,pub pixel_shader:u64,pub command_object:u64,pub render_target:u64,pub triangle_pixels:u64,pub before_hash:u64,pub after_hash:u64,pub live_hash:u64,pub queue_submitted:u64,pub queue_retired:u64,pub fence:u32,pub verified:bool}
fn pixel(base:u64,stride:u32,x:u32,y:u32,v:u32){let off=u64::from(y)*u64::from(stride)+u64::from(x)*4;unsafe{ptr::write_volatile((base+off) as *mut u32,v)}}
fn sample(base:u64,stride:u32,width:u32,height:u32)->u64{let mut h=0xcbf29ce484222325u64;for (x,y) in [(0,0),(width/4,height/4),(width/2,height/2),(width.saturating_sub(1),height.saturating_sub(1))]{let off=u64::from(y)*u64::from(stride)+u64::from(x)*4;let v=unsafe{ptr::read_volatile((base+off) as *const u32)};h^=u64::from(v);h=h.wrapping_mul(0x100000001b3)}h}
fn raster_triangle(base:u64,bytes:u64,width:u32,height:u32,stride:u32)->Result<u64,&'static str>{if base==0||u64::from(stride)*u64::from(height)>bytes{return Err("C31 render target bounds invalid")};let tw=width.min(640).max(64);let th=height.min(360).max(64);let x0=width.saturating_sub(tw)/2;let y0=height.saturating_sub(th)/2;let ax=(x0+tw/2) as i64;let ay=y0 as i64;let bx=x0 as i64;let by=(y0+th-1) as i64;let cx=(x0+tw-1) as i64;let cy=(y0+th-1) as i64;let edge=|x0:i64,y0:i64,x1:i64,y1:i64,x:i64,y:i64|(x-x0)*(y1-y0)-(y-y0)*(x1-x0);let area=edge(ax,ay,bx,by,cx,cy);if area==0{return Err("C31 triangle degenerate")};let mut n=0u64;for y in y0..y0+th{for x in x0..x0+tw{let px=x as i64;let py=y as i64;let w0=edge(bx,by,cx,cy,px,py);let w1=edge(cx,cy,ax,ay,px,py);let w2=edge(ax,ay,bx,by,px,py);if (area>0&&w0>=0&&w1>=0&&w2>=0)||(area<0&&w0<=0&&w1<=0&&w2<=0){let color=0x00ff_40d0u32 ^ ((x&0x3f)<<8) ^ (y&0x3f);pixel(base,stride,x,y,color);n+=1}}}if n<512{return Err("C31 triangle rasterized too few pixels")};Ok(n)}
fn execute_reference(cmd:&CommandBuffer,pipe:radeon_pipeline::GraphicsPipeline,target:u64,bytes:u64)->Result<u64,&'static str>{let mut bind=false;let mut draw=false;for i in 0..cmd.command_count(){let c=cmd.decode(i)?;match c.opcode{CommandOpcode::BindPipeline=>{if c.a!=pipe.id{return Err("C31 graphics pipeline command mismatch")};bind=true},CommandOpcode::DrawTriangle=>{draw=true},_=>{}}}if !bind||!draw{return Err("C31 graphics command stream incomplete")};raster_triangle(target,bytes,pipe.width,pipe.height,pipe.stride)}
pub fn qualify(allocator:&mut FrameAllocator<'_>,boot_info:&BootInfo,owner:u64,c30:C30State)->Result<GraphicsQualification,&'static str>{
 let target=radeon_memory::object(owner,c30.back_object).ok_or("C31 C30 back scanout object unavailable")?;if target.kernel_virtual==0{return Err("C31 render target not CPU mapped")};let stride=c30.width.checked_mul(4).ok_or("C31 render stride overflow")?;
 let vs=radeon_shader::upload(allocator,owner,ShaderStage::Vertex,ReferenceShaderKind::TriangleVertex,&radeon_shader::VERTEX_TRIANGLE)?;let ps=radeon_shader::upload(allocator,owner,ShaderStage::Pixel,ReferenceShaderKind::SolidPixel,&radeon_shader::PIXEL_SOLID)?;radeon_shader_cache::insert(vs,true)?;radeon_shader_cache::insert(ps,true)?;
 let pipe=radeon_pipeline::graphics(0xc031_0002,vs,ps,target.id,c30.width,c30.height,stride)?;let mut cmd=CommandBuffer::allocate(allocator,owner)?;cmd.emit(CommandOpcode::BindPipeline,pipe.id,0,0,0)?;cmd.emit(CommandOpcode::BindResource,0,target.id,target.gpu_virtual,target.mapped_bytes)?;cmd.emit(CommandOpcode::DrawTriangle,3,1,0,0)?;cmd.emit(CommandOpcode::Present,target.id,u64::from(c30.width),u64::from(c30.height),u64::from(stride))?;
 let before=sample(target.kernel_virtual,stride,c30.width,c30.height);let mut fence=RadeonFenceTimeline::allocate(allocator,owner)?;let(seq,_)=fence.issue()?;let mut q=ExecutionQueue::new(QueueClass::Graphics);let sid=q.submit(cmd.object_id(),seq)?;if q.start_head()?!=sid{return Err("C31 graphics queue start id mismatch")};let pixels=execute_reference(&cmd,pipe,target.kernel_virtual,target.mapped_bytes)?;let after=sample(target.kernel_virtual,stride,c30.width,c30.height);if after==before{return Err("C31 graphics draw did not alter render target fingerprint")};let mut fb=Framebuffer::from_boot_info(boot_info)?;let _=fb.copy_xrgb8888(target.kernel_virtual,stride,c30.width,c30.height)?;let live=fb.sample_hash();if live==0{return Err("C31 live framebuffer fingerprint invalid")};fence.complete_software(seq);if q.retire_head(fence.completed())?!=sid{return Err("C31 graphics retirement failed")};let(_,submitted,retired,count)=q.counters();if count!=0||submitted!=1||retired!=1{return Err("C31 graphics queue counters invalid")};Ok(GraphicsQualification{vertex_shader:vs.object_id,pixel_shader:ps.object_id,command_object:cmd.object_id(),render_target:target.id,triangle_pixels:pixels,before_hash:before,after_hash:after,live_hash:live,queue_submitted:submitted,queue_retired:retired,fence:seq,verified:true})
}
