//! K10 anti-rollback and A/B update activation state.
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum Slot{A,B}#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum UpdateState{Idle,Staged,Verified,PendingBoot,Confirmed,Reverted,Failed}
#[derive(Clone,Copy,Debug)]pub struct UpdateManager{pub active:Slot,pub pending:Option<Slot>,pub state:UpdateState,pub installed_version:u64,pub rollback_floor:u64,pub boot_attempts:u8,pub maximum_boot_attempts:u8}
impl UpdateManager{pub const fn new(version:u64)->Self{Self{active:Slot::A,pending:None,state:UpdateState::Idle,installed_version:version,rollback_floor:version,boot_attempts:0,maximum_boot_attempts:3}}
 pub fn stage(&mut self,target:Slot,version:u64)->Result<(),&'static str>{if target==self.active{return Err("update target must be inactive slot")}if version<self.rollback_floor{return Err("update rejected by anti-rollback floor")}if !matches!(self.state,UpdateState::Idle|UpdateState::Confirmed|UpdateState::Reverted|UpdateState::Failed){return Err("update already in progress")}self.pending=Some(target);self.installed_version=version;self.state=UpdateState::Staged;self.boot_attempts=0;Ok(())}
 pub fn mark_verified(&mut self)->Result<(),&'static str>{if self.state!=UpdateState::Staged{return Err("update is not staged")}self.state=UpdateState::Verified;Ok(())}
 pub fn activate(&mut self)->Result<Slot,&'static str>{if self.state!=UpdateState::Verified{return Err("update is not verified")}let s=self.pending.ok_or("missing pending slot")?;self.state=UpdateState::PendingBoot;Ok(s)}
 pub fn record_boot(&mut self)->Result<(),&'static str>{if self.state!=UpdateState::PendingBoot{return Err("no pending update boot")}self.boot_attempts=self.boot_attempts.saturating_add(1);if self.boot_attempts>self.maximum_boot_attempts{self.pending=None;self.state=UpdateState::Reverted;return Err("update boot attempts exceeded; reverted")}Ok(())}
 pub fn confirm(&mut self)->Result<(),&'static str>{if self.state!=UpdateState::PendingBoot{return Err("update is not pending confirmation")}self.active=self.pending.take().ok_or("missing pending slot")?;self.rollback_floor=self.rollback_floor.max(self.installed_version);self.state=UpdateState::Confirmed;self.boot_attempts=0;Ok(())}
 pub fn fail_and_revert(&mut self){self.pending=None;self.state=UpdateState::Reverted;self.boot_attempts=0}}
